# Generated by Django 4.2.4 on 2023-08-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kortaks_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
