# Generated by Django 4.2.4 on 2023-08-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kortaks_api', '0003_alter_song_unique_together_alter_song_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songnumber',
            unique_together={('song', 'album'), ('album', 'album_number')},
        ),
    ]
