# Generated by Django 4.2.4 on 2023-08-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kortaks_api', '0004_alter_songnumber_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songnumber',
            unique_together={('album', 'album_number')},
        ),
        migrations.AddField(
            model_name='songnumber',
            name='albums',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='kortaks_api.song'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='songnumber',
            unique_together={('album', 'album_number'), ('albums', 'album')},
        ),
        migrations.RemoveField(
            model_name='songnumber',
            name='song',
        ),
    ]
