# Generated by Django 4.2.4 on 2023-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kortaks_api', '0006_alter_executor_title_alter_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='slug',
            field=models.SlugField(default='sdfg', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=12, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executor',
            name='title',
            field=models.CharField(max_length=125, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
